### ISSUE TITLE
Jenkins is not waiting for the end of the Test Campaign

### ISSUE THREAD

**Issue by MrKartec** [cerberustesting/cerberus-jenkins-plugin#13]
Hi.

I've configured the Cerberus Jenkins Plugin.
I'm able to launch a campaign through it, but the issue is that it does not wait for the end of the execution to set the build status.

Using the default "google" test in a simple test campaign, Jenkins reports a successful build even if the google test failed and before it was even finished.

Build logs:
```
[INFO] [2017-12-26 11:04:24.424] Launch campaign TestCampaign on http://cerberus_as_glassfish:8080/Cerberus with tag 20171226110424012
[INFO] [2017-12-26 11:04:24.424] Campaign is launched successfully. You can follow the report here : http://cerberus_as_glassfish:8080/Cerberus/ReportingExecutionByTag.jsp?Tag=20171226110424012
[INFO] [2017-12-26 11:04:24.424] Campaign execution is finished. You can view the report here : http://cerberus_as_glassfish:8080/Cerberus/ReportingExecutionByTag.jsp?Tag=20171226110424012
Finished: SUCCESS
```

In the cerberus report, I have:
```
Start: Dec 26, 2017 11:04:24 AM
End:   Dec 26, 2017 11:04:33 AM
1 test - 100% failed
```

**Comment by nicodeur** [comment]
Hi @MrKartec ,

What is the status of the campaign at http://cerberus_as_glassfish:8080/Cerberus/ReportingExecutionByTag.jsp?Tag=20171226110424012 ?

Default "google" is an old test, and I not sure it still works fine ....

**Comment by MrKartec** [comment]
I don't have this environment anymore. But I can reproduce with one of our test on an other server.

___

For this one, our robot was offline.

Here is the jenkins log:

```
Building in workspace /var/jenkins_home/workspace/Test 1
[INFO] [2017-12-29 11:10:10.1010] Launch campaign Test 1 on http://*** with tag 20171229111010391
[INFO] [2017-12-29 11:10:10.1010] Campaign is launched successfully. You can follow the report here : http://***/ReportingExecutionByTag.jsp?Tag=20171229111010391
[INFO] [2017-12-29 11:10:10.1010] Campaign execution is finished. You can view the report here : http://***/ReportingExecutionByTag.jsp?Tag=20171229111010391
Finished: SUCCESS
```

Cerberus reported 100% QU.

I also noticed that the logs entry on Jenkins are all at the same timestamp, so I checked on a successful campaign: 

```
[INFO] [2017-12-29 11:21:01.211] Launch campaign Test 1 on http://*** with tag 20171229112101644
[INFO] [2017-12-29 11:21:01.211] Campaign is launched successfully. You can follow the report here : http://***/ReportingExecutionByTag.jsp?Tag=20171229112101644
[INFO] [2017-12-29 11:21:01.211] Campaign execution is finished. You can view the report here : http://***/ReportingExecutionByTag.jsp?Tag=20171229112101644
Finished: SUCCESS
```

And for Cerberus
```
start: Dec 29, 2017 11:21:01 AM
end: Dec 29, 2017 11:21:22 AM
```

**Comment by nicodeur** [comment]
Can you precise your Cerberus version, an your jenkins-plugin version ?

When Campaign is running, can you chek the result of api `urlCerberus + "/ResultCIV002?tag=" + tagCerberus`  and report json reult here ?

**Comment by vertigo17** [comment]
If tests are in QU state that means that the executions did not even triggered.
Can you check the Queue entry message (comment fields in queue entry modal).
It will tell you why the execution did not triggered.
I guess it could be that the parameter cerberus_url has not been set correctly. Make sure to follow the INSTALL procedure that mention the parameters that are mandatory to define at first installation of Cerberus.
https://github.com/cerberustesting/cerberus-source/blob/master/INSTALL
In your case, it should be defined to something like:
http://cerberus_as_glassfish:8080/Cerberus

**Comment by MrKartec** [comment]
@nicodeur 
I won't be at the office for two weeks and I won't be able access the environment from here. I'll ask someone to check the version of both Cerberus and the plugin and to test the API endpoint.
I'll report back ASAP.

___
@vertigo17 
The issue here isn't that the tests are in QU, (I forced this by shutting down the Selenium hub) but that Jenkins is reporting it as a success and before Cerberus is even done.

`cerberus_url` is properly set to the url at which Cerberus is accessible.

**Comment by MrKartec** [comment]
Cerberus : 2.0.0-1237
Plugin : 1.0.3


Here is what I get when I call the url during execution:
```json
{
  "NonOK_prio1_nbOfExecution": 0,
  "status_PE_nbOfExecution": 1,
  "TOTAL_nbOfExecution": 4,
  "CI_OK_prio1": 1,
  "status_CA_nbOfExecution": 0,
  "status_QU_nbOfExecution": 2,
  "status_FA_nbOfExecution": 1,
  "message": "CI result calculated with success.",
  "status_NA_nbOfExecution": 0,
  "result": "PE",
  "ExecutionStart": "2018-01-15 15:34:20.0",
  "status_OK_nbOfExecution": 0,
  "messageType": "OK",
  "NonOK_prio3_nbOfExecution": 0,
  "status_KO_nbOfExecution": 0,
  "NonOK_prio4_nbOfExecution": 0,
  "tag": "Test 1 - 20180115153420070",
  "CI_finalResult": 0,
  "CI_OK_prio3": 0.20000000298023224,
  "CI_OK_prio2": 0.5,
  "ExecutionEnd": "2018-01-15 15:36:11.0",
  "NonOK_prio2_nbOfExecution": 0,
  "CI_OK_prio4": 0.10000000149011612,
  "status_NE_nbOfExecution": 0
}
```
  
And once it's done
```json
{
  "NonOK_prio1_nbOfExecution": 0,
  "status_PE_nbOfExecution": 0,
  "TOTAL_nbOfExecution": 4,
  "CI_OK_prio1": 1,
  "status_CA_nbOfExecution": 0,
  "status_QU_nbOfExecution": 0,
  "status_FA_nbOfExecution": 1,
  "message": "CI result calculated with success.",
  "status_NA_nbOfExecution": 0,
  "result": "OK",
  "ExecutionStart": "2018-01-15 15:34:20.0",
  "status_OK_nbOfExecution": 3,
  "messageType": "OK",
  "NonOK_prio3_nbOfExecution": 0,
  "status_KO_nbOfExecution": 0,
  "NonOK_prio4_nbOfExecution": 0,
  "tag": "Test 1 - 20180115153420070",
  "CI_finalResult": 0,
  "CI_OK_prio3": 0.20000000298023224,
  "CI_OK_prio2": 0.5,
  "ExecutionEnd": "2018-01-15 15:37:03.0",
  "NonOK_prio2_nbOfExecution": 0,
  "CI_OK_prio4": 0.10000000149011612,
  "status_NE_nbOfExecution": 0
}
```

**Comment by nicodeur** [comment]
Hello @MrKartec ,

I saw you use spaces on tag (`Test 1 - 20180115153420070`).

When I look at log on your first message, only the timestamp appears `(Test 1 - ` is not displayed)  Can you test without spaces ?

**Comment by MrKartec** [comment]
The first log didn't have the timestamp in his test configuration.
But I tried anyway and the result is the same.

**Comment by nicodeur** [comment]
Hello @MrKartec 

After check the code, it could due to the `Timeout for campaign execution` parameter is set to 0.

This parameter is present on   `Manage Jenkins/Configure System/Cerberus` Jenkins page. Can you verify it ? My own parameter is on 21600.

**Comment by MrKartec** [comment]
Hi !

You're right, setting the campaign timeout fixed the problem.

Thank you !

**Comment by nicodeur** [comment]
Nice!

This parameter should be set by default to 14400 by this [file](https://github.com/cerberustesting/cerberus-jenkins-plugin/blob/master/src/main/resources/org/cerberus/jenkinsci/plugins/executecerberustest/ExecuteCerberusCampaign/global.jelly) 

Do you know if it was setting by default on 0 on your jenkins, or if it was a human setting ?

**Comment by MrKartec** [comment]
I can't remember, so I tried on a fresh installation of Jenkins with Docker and cerberus-jenkins-plugin@1.0.3 and here is the default configuration.

![4eec87ba-74f9-4c34-9233-b62e7fb3dfea](https://user-images.githubusercontent.com/9460143/35033523-470cd50e-fb6b-11e7-9782-54c251071c9c.png)

**Comment by nicodeur** [comment]
Hi @MrKartec ,

Cerberus use a `priority` on `test case` to manage if a test is ko, the result of campaign is KO too. For minor bug, you should don't broken your pipeline by exemple.

So, you can modify this priority on `Test case list` -> `Edit test case` -> Enter the `1-Critical Priority` for exemple

**Comment by vertigo17** [comment]
@nicodeur , can you confirm that jenkins plugin use "result" = "OK" data from public servlet in order to decide the final status ? 

@MrKartec , that field with a score that is calculated against priority level defined at testcase level and correspondind ponderation rates inside parameter screen under Cerberus.
parameters from cerberus_ci_okcoefprio1 to cerberus_ci_okcoefprio5 in SNAPSHOT version.

You can have a look at documentation of the public servlet ResultCIV002 calling it with no parameter it will explain how calculation is done:

_This servlet is used to provide various execution counters as well as a global OK or KO status based on the number and status of the execution done on a specific tag. 
The number of executions are ponderated by parameters by priority from cerberus_ci_okcoefprio1 to cerberus_ci_okcoefprio4. 
Formula used is the following : 
Nb Exe Prio 1 testcases * cerberus_ci_okcoefprio1 + Nb Exe Prio 2 testcases * cerberus_ci_okcoefprio2 + Nb Exe Prio 3 testcases * cerberus_ci_okcoefprio3 + Nb Exe Prio 4 testcases * cerberus_ci_okcoefprio4.
If no executions are found, the result is KO.
With at least 1 execution, if result is < 1 then global servlet result is OK. If not, it is KO.
All execution needs to have a status equal to KO, FA, NA, PE or NE.
If at least 1 PE or 1 NE if found, global status will be PE
Output format is json by default, or SVG if outputFormat=svg is defined
Parameter list :
- tag [mandatory] : Execution Tag to filter the test cases execution. []
- outputFormat    : ['json', 'svg']. Output format of the result. []_

**Comment by nicodeur** [comment]
Yes, I confirm Jenkins plugin use "result" = "OK".

Thanks for precision @vertigo17 !

**Comment by vertigo17** [comment]
With last comit https://github.com/cerberustesting/cerberus-jenkins-plugin/commit/ebb878ac6ee3e4a93030a64eaa972609d036785d I added in the log the Result CI calculation score :

[INFO] [2018-06-09 11:33:00.330] ---------------------------------------------------------------------------------------------
[INFO] [2018-06-09 11:33:00.330] Result : OK (Score : **0.20000000298023224**), campaign executed in 70s.
[INFO] [2018-06-09 11:33:00.330] Details : OK 8 | KO 2 | FA 0 | NA 0 | NE 0 | WE 0 | PE 0 | QU 0 | QE 0 | CA 0
[INFO] [2018-06-09 11:33:00.330] ---------------------------------------------------------------------------------------------

That will make debug easier.
