### ISSUE TITLE
Variable interpolation does not work on several text fields

### ISSUE THREAD

**Issue by cjmachado** [cerberustesting/cerberus-jenkins-plugin#14]
Trying to use a variable or parameter on several text fields renders the variable itself and not its value. All text fields should allow variable interpolation for maximum flexibility (values that are passed as job parameters, for instance).

Steps to reproduce the issue:
1. Create a job with a String parameter, for instance CAMPAIGN;
2. Add 'Execute Cerberus Campaign' build step;
3. Set the value of 'Campaign to launch:' field to ${CAMPAIGN}
4. Save the job configuration;
5. Click on Build with parameters;
6. Specify a value for CAMPAIGN parameter, for instance MyCampaign;
7. Console output is:

[INFO] [2018-02-07 06:09:11.911] Launch campaign **${CAMPAIGN}** on http://1.2.3.4/Cerberus with tag MyApp_201802071809
[INFO] [2018-02-07 06:09:11.911] Campaign is launched successfully. You can follow the report here : http://1.2.3.4/Cerberus/ReportingExecutionByTag.jsp?Tag=MyApp_201802071809
[INFO] [2018-02-07 06:09:11.911] ---------------------------------------------------------------------------------------------
[INFO] [2018-02-07 06:09:11.911] Result : KO, test executed in 0s 0ms
[INFO] [2018-02-07 06:09:11.911] Details : OK 0 | CA 0 | FA 0 | NA 0 | KO 0 | PE 0 | QU 0 | NE 0
[INFO] [2018-02-07 06:09:11.911] ---------------------------------------------------------------------------------------------
[ERROR] [2018-02-07 06:09:11.911] FAIL

Notice the text in **bold**. The expected value would be "MyCampaign".

**Comment by nicodeur** [comment]
Hi,
Pull request is validated,
Will be fixed at the next release.

Regards,
