### ISSUE TITLE
Jenkins Job keep running "forever"

### ISSUE THREAD

**Issue by mbessa** [cerberustesting/cerberus-jenkins-plugin#15]
If some executions were with state "_Queue error_" jenkins job keep running until is manually stopped.

You can check the following example:
- http://jenkinspt.siege.red:8210/job/productreferences-availability-TESTING-QA/24/console
- http://cerberus.siege.red/Cerberus/ReportingExecutionByTag.jsp?Tag=productreferences-availability_20180323172431

Can you please fix this behavior?

Thank you,
Marco

**Comment by vertigo17** [comment]
That should be fixed with latest that will handle all execution status  comit https://github.com/cerberustesting/cerberus-jenkins-plugin/commit/ebb878ac6ee3e4a93030a64eaa972609d036785d
It will be available in 1.0.5
