### ISSUE TITLE
Problem Jenkins : Connection refused 

### ISSUE THREAD

**Issue by glassalle59** [cerberustesting/cerberus-jenkins-plugin#18]
Hello,

I have a problem when I try to execute the job to launch a campaign in Cerberus.
Cerberus and Jenkins on Docker

There is my config:

<img width="1066" alt="capture d ecran 2018-06-05 a 16 48 28" src="https://user-images.githubusercontent.com/33724879/40983646-5f03a132-68e0-11e8-8fbd-86a5a58ca9fe.png">

<img width="929" alt="capture d ecran 2018-06-05 a 16 48 40" src="https://user-images.githubusercontent.com/33724879/40983655-63ebac08-68e0-11e8-8895-1aaf853b6e46.png">

The logs:
<img width="1064" alt="capture d ecran 2018-06-05 a 16 49 37" src="https://user-images.githubusercontent.com/33724879/40983715-82ce3000-68e0-11e8-8ee9-0e7320b06659.png">

**Comment by nicodeur** [comment]
Hello,

Can you precise Cerberus version and Cerberus Jenkins Plugin version please ?

Avec you verify than Jenkins have an access to http://localhost:18080/Cerberus ? Jenkins is running directly on you computer or with a docker container on your computer ?

**Comment by glassalle59** [comment]
Cerberus 3.5 (the latest)
Cerberus Jenkins Plugin 1.0.3 (the latest)

Jenkins and Cerberus is running both on a docker computer on my computer

**Comment by nicodeur** [comment]
If you use docker for both, cerberus url since jenkins shouldn't be `localhost:18080`, but `container_name:8080`. 2 containers must be on the same docker network.

If 2  containers are not on the same docker network, you can use real IP of your host (ìp:18080`)

**Comment by vertigo17** [comment]
There also seems to have a warning on robot not defined.
I beleive that this was simplified on latest version. 
@nicodeur Did we perform a new release since the last changes ?

**Comment by vertigo17** [comment]
Can you try to feed the environment and/or robot ?
Latest changes on jenkins plugin should have the exact URL request sent to Cerberus in the log in order to make debuging easier but I beleive that we did not release yet.

**Comment by glassalle59** [comment]
Same !

_Started by user Lassalle
Building in workspace /var/jenkins_home/workspace/Cerberus_Campaign_Launcher
[INFO] [2018-06-06 08:15:40.1540] Launch campaign LOCALCAMPAIGN on http://localhost:8080/Cerberus with tag JENKINS-20180606081540400
[ERROR] [2018-06-06 08:15:40.1540] Error message when trying to add a new exectution in queue : Not Found
[ERROR] [2018-06-06 08:15:40.1540] Fail to add campaign LOCALCAMPAIGN in cerberus queue
[ERROR] [2018-06-06 08:15:40.1540] Think to check cerberus log or cerberus queue to resolve problem
[ERROR] [2018-06-06 08:15:40.1540] UNSTABLE
Build step 'Execute Cerberus Campaign' changed build result to FAILURE
Finished: FAILURE__

**Comment by nicodeur** [comment]
Can you explain your docker settings please ?

I just release a new Jenkins Cerberus  Release (1.0.4), you can test with it (available in 4h maximum)

**Comment by glassalle59** [comment]
What informations do you want exactly. ?

**Comment by nicodeur** [comment]
How do you run your Jenkins ? your Cerberus ?

I would like : 
* either  `docker-compose` file, or `docker run` command.
* Result of `docker ps` command.
* Log of ceberus (`docker logs <container_name>` or `docker-compose logs`) while jenkins try to add a new execution  in queue

**Comment by glassalle59** [comment]
I installed Cerberus with the command : docker-compose -f default.yml up
I installed Jenkins via Kitematic (https://hub.docker.com/_/jenkins/)

Result of docker ps:

<img width="1344" alt="capture d ecran 2018-06-07 a 09 40 46" src="https://user-images.githubusercontent.com/33724879/41085315-ec735722-6a36-11e8-8058-d34e0eb44b25.png">

Logs of Jenkins when try to add a new execution in queue : 
_INFO: Cerberus_Campaign_Launcher #24 main build action completed: FAILURE
Jun 06, 2018 2:12:31 PM hudson.model.AsyncPeriodicWork$1 run_

(I haven't any logs on Cerberus)

**Comment by vertigo17** [comment]
Next release 1.0.5 will put in the log the detailed URL called from Jenkins to Cerberus.
That will help debug.

**Comment by vertigo17** [comment]
following conversation, I close the issue.
Please reopen on the official jenkins repo or cerberus repo as I beleive this now moved to a cerberus issue.
