### ISSUE TITLE
Planning campain & sending email

### ISSUE THREAD

**Issue by vitoo** [cerberustesting/cerberus-jenkins-plugin#6]
Hello,

Do you know if we can easily manage plan of campain in jenkins (like cron task) 

And if we can send the result by email within jenkins (ex : 95% tests OK) 

Thanks

**Comment by nicodeur** [comment]
Hi,

Yes, with Jenkins, you can easily launch a campaign each days/hours etc. Jenkins use cron to make it : 
![image](https://user-images.githubusercontent.com/6707556/29401243-ba0e0d6a-8330-11e7-9d85-4b123ce4bc8d.png)

To send an email with the result, there is an issue open on cerberus : https://github.com/cerberustesting/cerberus-source/issues/1408

For the time, you can sent an email with Jenkins with the result of Job. Job has 3 states : 
- OK : 100% Tests are OK
- UNSTABLE : At least 1 test are KO (with test priority, you can say if 1 test are KO, result of job rest OK)
- ERROR : an error has occured (connection error by exemple).

You can also sent log of job by email.  It looks like this:
```
[INFO] [2017-08-14 06:21:57.2157] Campaign is launched successfully. You can follow the report here : http://cerberus.siege.red/Cerberus/ReportingExecutionByTag.jsp?Tag=finpmt-propose_20170814182156
[INFO] [2017-08-14 06:21:57.2157] 0 test executed ... (Details : OK 0 | CA 0 | FA 0 | NA 0 | KO 0 | PE 0 | QU 120 | NE 0)
[INFO] [2017-08-14 06:21:57.2157] 0 test pending ...
[INFO] [2017-08-14 06:21:57.2157] cerberus message : CI result calculated with success.
[INFO] [2017-08-14 06:21:57.2157] Advancement : 0%
[INFO] [2017-08-14 06:22:17.2217] 6 test executed ... (Details : OK 2 | CA 0 | FA 0 | NA 0 | KO 4 | PE 2 | QU 118 | NE 0)
[INFO] [2017-08-14 06:22:17.2217] 2 test pending ...
[INFO] [2017-08-14 06:22:17.2217] cerberus message : CI result calculated with success.
[INFO] [2017-08-14 06:22:17.2217] Advancement : 75%
[INFO] [2017-08-14 06:22:37.2237] 14 test executed ... (Details : OK 6 | CA 0 | FA 0 | NA 0 | KO 8 | PE 2 | QU 114 | NE 0)
[INFO] [2017-08-14 06:22:37.2237] 2 test pending ...
.....
.....
.....
[INFO] [2017-08-14 06:33:39.3339] 119 test executed ... (Details : OK 78 | CA 0 | FA 10 | NA 0 | KO 31 | PE 1 | QU 1 | NE 0)
[INFO] [2017-08-14 06:33:39.3339] 1 test pending ...
[INFO] [2017-08-14 06:33:39.3339] cerberus message : CI result calculated with success.
[INFO] [2017-08-14 06:33:39.3339] Advancement : 99%
[INFO] [2017-08-14 06:33:59.3359] ---------------------------------------------------------------------------------------------
[INFO] [2017-08-14 06:33:59.3359] Result : KO, test executed in 693s 0ms
[INFO] [2017-08-14 06:33:59.3359] Details : OK 79 | CA 0 | FA 10 | NA 0 | KO 31 | PE 0 | QU 0 | NE 0
[INFO] [2017-08-14 06:33:59.3359] ---------------------------------------------------------------------------------------------
[ERROR] [2017-08-14 06:33:59.3359] FAIL
[INFO] [2017-08-14 06:33:59.3359] 120 test executed ... (Details : OK 79 | CA 0 | FA 10 | NA 0 | KO 31 | PE 0 | QU 0 | NE 0)
[INFO] [2017-08-14 06:33:59.3359] 0 test pending ...
[INFO] [2017-08-14 06:33:59.3359] cerberus message : CI result calculated with success.
[INFO] [2017-08-14 06:33:59.3359] Advancement : 100%
[INFO] [2017-08-14 06:33:59.3359] Campaign execution is finished. You can view the report here : http://cerberus.siege.red/Cerberus/ReportingExecutionByTag.jsp?Tag=finpmt-propose_20170814182156
Build step 'Execute Cerberus Campaign' changed build result to UNSTABLE
```

Nicolas

**Comment by vitoo** [comment]
The mail functionnality will be compatible with jenkins plugin ?

What url use jenkins cerberus plugin ?

**Comment by nicodeur** [comment]
The mail functionnality will be configurable on Cerberus. So Yes, when a campaign will be executed by jenkins plugin, mail will be sent.

Jenkins plugin just call AddToExecutionQueue cerberus service. Tests is added to cerberus queue, and it's cerberus queue who manage Test execution.

**Comment by vitoo** [comment]
Hello @nicodeur @bcivel 

Can you plan a new cerberus docker release ? Arround 1st september ?
My mission ends the 8 september
And I would like to have the email fonctionnality for my devs team

I will try jenins pluggin v1.0.1 for my actual cerberus 1.1.12

Thanks a lot

**Comment by vitoo** [comment]
Well, with the plugin v1.0.1 i dont have cerberus parameters in the  "Manage Jenkins"

**Comment by nicodeur** [comment]
Hi @vitoo,

We will see to do a new Cerberus release asap. We keep you informed.

Regards
